version: '3.8'

services:
  postgres-db:
    build:
      context: ./django_site_db
    # image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
 
  django:
    build:
      context: ./django_site
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    env_file:
      - .env
      
    volumes:
      - ./django_site:/app
      - static_volume:/app/static

  react:
    build:
      context: ./django_site-app
    container_name: react
    ports:
      - "3000:3000"
    depends_on:
      - django
    volumes:
      - static_volume:/app/static
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - react
      - django


volumes:
  pg_data:
  static_volume: