version: '3.8'
x-environment-defaults: &environment-defaults
  DEBUG: "False"
  DB_NAME: "django_db"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "postgres-db"
  DB_PORT: 5432
  SECRET_KEY: "secret"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data
  # django:
  #   build:
  #     context: ./django_site
  #   container_name: django
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres-db
  #   environment:
  #     <<: *environment-defaults
    
# volumes:
#   pg_data:
#   static_volume: