version: '3.8'
x-environment-defaults: &environment-defaults
  DB_NAME: "django_db"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "postgres-db"
  DB_PORT: 5432
  SECRET_KEY: "secret"
  STRIPE_PUBLISH_KEY: "pk_test_51OIq5AHiwmBkzbO7aqsO6kNsxv6mxxvFtTini2ZEJIyDFV3zkiJSlKgIo5QlIOve2sgIFh6yfxpF2Mziuq5ZnZZF00vcgY1UWV"
  STRIPE_SECRET_KEY: "sk_test_51OIq5AHiwmBkzbO7tuMC2r3q9DuK0Smgwt7K3UQXnAgT54OPiR9gFM1xZ2g8Lmk3HQgn3PdfW96WWTp50SktpXX200y88qhHkG"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
 
  django:
    build:
      context: ./django_site
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    environment:
      <<: *environment-defaults
      
    volumes:
      - ./django_site:/app
      - static_volume:/app/static

  react:
    build:
      context: ./django_site-app
    container_name: react
    ports:
      - "3000:3000"
    depends_on:
      - django
    volumes:
      - static_volume:/app/static
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - react
      - django


volumes:
  pg_data:
  static_volume: